package modify

import (
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockModifyProcessor is a mock implementation for modify operations testing
type MockModifyProcessor struct {
	mock.Mock
}

// Insert mocks the insert method
func (m *MockModifyProcessor) Insert(table string, data map[string]interface{}) (int64, error) {
	args := m.Called(table, data)
	return args.Get(0).(int64), args.Error(1)
}

// Update mocks the update method
func (m *MockModifyProcessor) Update(table string, data map[string]interface{}, where string) (int64, error) {
	args := m.Called(table, data, where)
	return args.Get(0).(int64), args.Error(1)
}

// Delete mocks the delete method
func (m *MockModifyProcessor) Delete(table string, where string) (int64, error) {
	args := m.Called(table, where)
	return args.Get(0).(int64), args.Error(1)
}

// Close mocks the close method
func (m *MockModifyProcessor) Close() error {
	args := m.Called()
	return args.Error(0)
}

func TestInsertOperations(t *testing.T) {
	// Test basic insert operations
	t.Run("BasicInsert", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		insertData := map[string]interface{}{
			"name":  "test_user",
			"email": "test@example.com",
			"age":   25,
		}
		mockProcessor.On("Insert", "users", insertData).Return(int64(1), nil)
		
		// Execute
		id, err := mockProcessor.Insert("users", insertData)
		
		// Assert
		assert.NoError(t, err)
		assert.Equal(t, int64(1), id)
		mockProcessor.AssertExpectations(t)
	})
	
	t.Run("InsertWithAutoGeneratedKey", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		insertData := map[string]interface{}{
			"name":        "auto_key_user",
			"description": "User with auto-generated key",
		}
		mockProcessor.On("Insert", "users", insertData).Return(int64(42), nil)
		
		// Execute
		id, err := mockProcessor.Insert("users", insertData)
		
		// Assert
		assert.NoError(t, err)
		assert.Equal(t, int64(42), id)
		mockProcessor.AssertExpectations(t)
	})
}

func TestInsertValidationError(t *testing.T) {
	// Test insert operations with validation errors
	t.Run("InsertWithMissingRequiredField", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		invalidData := map[string]interface{}{
			"email": "test@example.com",
			// Missing required "name" field
		}
		expectedError := assert.AnError
		mockProcessor.On("Insert", "users", invalidData).Return(int64(0), expectedError)
		
		// Execute
		id, err := mockProcessor.Insert("users", invalidData)
		
		// Assert
		assert.Error(t, err)
		assert.Equal(t, int64(0), id)
		mockProcessor.AssertExpectations(t)
	})
	
	t.Run("InsertWithInvalidDataType", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		invalidData := map[string]interface{}{
			"name":  "test_user",
			"age":   "not_a_number", // Invalid data type
			"email": "test@example.com",
		}
		expectedError := assert.AnError
		mockProcessor.On("Insert", "users", invalidData).Return(int64(0), expectedError)
		
		// Execute
		id, err := mockProcessor.Insert("users", invalidData)
		
		// Assert
		assert.Error(t, err)
		assert.Equal(t, int64(0), id)
		mockProcessor.AssertExpectations(t)
	})
}

func TestUpdateOperations(t *testing.T) {
	// Test basic update operations
	t.Run("BasicUpdate", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		updateData := map[string]interface{}{
			"name":  "updated_user",
			"email": "updated@example.com",
		}
		whereClause := "id = 1"
		mockProcessor.On("Update", "users", updateData, whereClause).Return(int64(1), nil)
		
		// Execute
		rowsAffected, err := mockProcessor.Update("users", updateData, whereClause)
		
		// Assert
		assert.NoError(t, err)
		assert.Equal(t, int64(1), rowsAffected)
		mockProcessor.AssertExpectations(t)
	})
	
	t.Run("UpdateMultipleRows", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		updateData := map[string]interface{}{
			"status": "active",
		}
		whereClause := "age > 18"
		mockProcessor.On("Update", "users", updateData, whereClause).Return(int64(25), nil)
		
		// Execute
		rowsAffected, err := mockProcessor.Update("users", updateData, whereClause)
		
		// Assert
		assert.NoError(t, err)
		assert.Equal(t, int64(25), rowsAffected)
		mockProcessor.AssertExpectations(t)
	})
}

func TestUpdateConstraintViolation(t *testing.T) {
	// Test update operations with constraint violations
	t.Run("UpdateWithUniqueConstraintViolation", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		updateData := map[string]interface{}{
			"email": "duplicate@example.com",
		}
		whereClause := "id = 1"
		expectedError := assert.AnError
		mockProcessor.On("Update", "users", updateData, whereClause).Return(int64(0), expectedError)
		
		// Execute
		rowsAffected, err := mockProcessor.Update("users", updateData, whereClause)
		
		// Assert
		assert.Error(t, err)
		assert.Equal(t, int64(0), rowsAffected)
		mockProcessor.AssertExpectations(t)
	})
}

func TestDeleteOperations(t *testing.T) {
	// Test basic delete operations
	t.Run("BasicDelete", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		whereClause := "id = 1"
		mockProcessor.On("Delete", "users", whereClause).Return(int64(1), nil)
		
		// Execute
		rowsAffected, err := mockProcessor.Delete("users", whereClause)
		
		// Assert
		assert.NoError(t, err)
		assert.Equal(t, int64(1), rowsAffected)
		mockProcessor.AssertExpectations(t)
	})
	
	t.Run("DeleteMultipleRows", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		whereClause := "status = 'inactive'"
		mockProcessor.On("Delete", "users", whereClause).Return(int64(15), nil)
		
		// Execute
		rowsAffected, err := mockProcessor.Delete("users", whereClause)
		
		// Assert
		assert.NoError(t, err)
		assert.Equal(t, int64(15), rowsAffected)
		mockProcessor.AssertExpectations(t)
	})
}

func TestDeleteReferentialIntegrity(t *testing.T) {
	// Test delete operations with referential integrity
	t.Run("DeleteWithForeignKeyConstraint", func(t *testing.T) {
		// Setup mock processor
		mockProcessor := new(MockModifyProcessor)
		whereClause := "id = 1"
		expectedError := assert.AnError
		mockProcessor.On("Delete", "users", whereClause).Return(int64(0), expectedError)
		
		// Execute
		rowsAffected, err := mockProcessor.Delete("users", whereClause)
		
		// Assert
		assert.Error(t, err)
		assert.Equal(t, int64(0), rowsAffected)
		mockProcessor.AssertExpectations(t)
	})
}